artifact_uri: file:///home/mle-user/mle-projects/mlflow-practice/mlflow_experiments_store/0/09a615f8d3f949b6bca1915907dfa307/artifacts
end_time: 1759855441535
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 09a615f8d3f949b6bca1915907dfa307
run_name: Default
run_uuid: 09a615f8d3f949b6bca1915907dfa307
source_name: ''
source_type: 4
source_version: ''
start_time: 1759855441526
status: 4
tags: []
user_id: mle-user
