artifact_uri: file:///home/mle-user/mle-projects/mlflow-practice/mlflow_experiments_store/0/4552b988b91b49fda7145ad5b3efc577/artifacts
end_time: 1759855494998
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4552b988b91b49fda7145ad5b3efc577
run_name: Default
run_uuid: 4552b988b91b49fda7145ad5b3efc577
source_name: ''
source_type: 4
source_version: ''
start_time: 1759855494989
status: 3
tags: []
user_id: mle-user
