artifact_location: file:///home/mle-user/mle-projects/mlflow-practice/mlflow_experiments_store/0
creation_time: 1758945357944
experiment_id: '0'
last_update_time: 1758945357944
lifecycle_stage: active
name: Default
