artifact_uri: file:///home/mle-user/mle-projects/mlflow-practice/mlflow_experiments_store/0/9c762c39c8c349e78ad76ec074314f3e/artifacts
end_time: 1759855422383
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9c762c39c8c349e78ad76ec074314f3e
run_name: Default
run_uuid: 9c762c39c8c349e78ad76ec074314f3e
source_name: ''
source_type: 4
source_version: ''
start_time: 1759855422362
status: 3
tags: []
user_id: mle-user
